# Generated by Django 4.0.4 on 2022-05-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(choices=[(2, 'client'), (1, 'company_client'), (0, 'admin')], default=2, verbose_name='사용자 레벨(client=2,company=1,admin=0)'),
        ),
    ]
